### ISSUE TITLE
Install and configure slurm

### ISSUE THREAD

**Issue by rburghol** [HARPgroup/cbp_wsm#52]
- Installed using apt, config based on 
  - https://slurm.schedmd.com/quickstart_admin.html
  - use configurator: https://slurm.schedmd.com/configurator.html
  - results pasted into `/etc/slurm-llnl/slurm.conf`
  - Note for standalone controller and compute node I used:
    - NodeName=deq2
    - SlurmctldHost=deq2
- Note: slurm prior to 20.11.7 or 20.02.7 are no longer available due to a security issue (Ubuntu dpkg is 19.x, has this been patched)
- install slurm with apt
-  This blog has some possibly good info for a standalone cluster on 20.04: 
  - https://blog.llandsmeer.com/tech/2020/03/02/slurm-single-instance.html
  - https://gist.github.com/ckandoth/2acef6310041244a690e4c08d2610423

APT - installed old version
```
sudo apt install slurm-wlm
mkdir /opt/model/slurm
sudo chown slurm:modelers /opt/model/slurm
sudo mkdir /var/spool/slurmctld
sudo chown slurm:modelers /var/spool/slurmctld

# config files: paste in configurator output: https://slurm.schedmd.com/configurator.html
nano /etc/slurm-llnl/slurm.conf
# copy basic cgroup.conf file 
cp /usr/share/doc/slurmd/examples/cgroup.conf /etc/slurm-llnl/

# get it all ready to run automatically 
sudo systemctl enable munge
sudo systemctl enable slurmctld
sudo systemctl enable slurmd

# start them up 
sudo systemctl start  munge
sudo systemctl start slurmctld
sudo systemctl start slurmd

```

- The install above seems to work, `sinfo` appears to generate reasonable info:
``` 
sinfo
PARTITION AVAIL  TIMELIMIT  NODES  STATE NODELIST
debug*       up   infinite      1   unk* deq2
```

- Make it go online
  - `sudo scontrol update NodeName=deq2 State=resume`
- list active jobs
  - `squeue`
- cancel a job
  - `scancel 12`

**Comment by rburghol** [comment]
Had problem starting slurmd (slurmctld started OK if slurm.conf is OK)
Needed to get cgroup.conf set up `cp /usr/share/doc/slurmd/examples/cgroup.conf /etc/slurm-llnl/`


Problem: slurmd wil not start on deq2 , so jobs never run on :
running `sudo systemctl status slurmd.service` yields:

```

● slurmd.service - Slurm node daemon
     Loaded: loaded (/lib/systemd/system/slurmd.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Wed 2022-02-23 19:03:00 UTC; 2min 1s ago
       Docs: man:slurmd(8)
    Process: 512228 ExecStart=/usr/sbin/slurmd $SLURMD_OPTIONS (code=exited, status=1/FAILURE)

Feb 23 19:03:00 deq2 systemd[1]: Starting Slurm node daemon...
Feb 23 19:03:00 deq2 systemd[1]: slurmd.service: Control process exited, code=exited, status=1/FAILURE
Feb 23 19:03:00 deq2 systemd[1]: slurmd.service: Failed with result 'exit-code'.
Feb 23 19:03:00 deq2 systemd[1]: Failed to start Slurm node daemon.

```

**Comment by rburghol** [comment]
On ubuntu 24.04
- small difference in paths
- Failed on first try to start service with `Active: failed (Result: exit-code) since Wed 2025-06-18 23:28:54 UTC; 49s ago`
   - How to find other details?
```
sudo apt install slurm-wlm
mkdir /opt/model/slurm
sudo chown slurm:modelers /opt/model/slurm
sudo mkdir /var/spool/slurmctld
sudo chown slurm:modelers /var/spool/slurmctld

sudo cp /usr/share/doc/slurmd/examples/cgroup.conf /etc/slurm/

# get it all ready to run automatically 
sudo systemctl enable munge
sudo systemctl enable slurmctld
sudo systemctl enable slurmd

# start them up 
sudo systemctl start  munge
sudo systemctl start slurmctld
sudo systemctl start slurmd


```


- Trying: `sudo scontrol update NodeName=deq3 State=resume`
   - `slurm_update error: Invalid node name specified`
- check log: 
   - `sudo tail /var/log/slurm*`
      - `==> /var/log/slurmctld.log <== error: Node deq3 appears to have a different slurm.conf than the slurmctld.  This could cause issues with communication and functionality.  Please review both files and make sure they are the same.  If this is expected ignore, and set DebugFlags=NO_CONF_HASH in your slurm.conf.`
- Find out what the node *should* have: `slurmd -C`
   - `NodeName=deq3 CPUs=24 Boards=1 SocketsPerBoard=1 CoresPerSocket=12 ThreadsPerCore=2 RealMemory=192676 UpTime=6-12:57:15`
- Vs. `fgrep NodeName /etc/slurm/slurm.conf`:
   - `NodeName=deq3 CPUs=24 Sockets=1 CoresPerSocket=12 ThreadsPerCore=2 State=UNKNOWN RealMemory=192676`
- Simply took the output from `slurmd -C` and set that in `/etc/slurm/slurm.conf`
- Still failed!  So, did `sudo scontrol reconfigure`
   - Jobs completed!

**Comment by rburghol** [comment]
https://www.linkedin.com/pulse/slurm-setup-easy-way-ubuntu-2404-practical-guide-building-nagaraj-s-tj7cc?utm_source=share&utm_medium=member_ios&utm_campaign=share_via

**Comment by rburghol** [comment]
Archived 20.04


#### 20.04 Installed using apt (see below), config based on 
  - https://slurm.schedmd.com/quickstart_admin.html
  - use configurator: https://slurm.schedmd.com/configurator.html
  - results pasted into `/etc/slurm-llnl/slurm.conf`
  - Note for standalone controller and compute node I used:
    - NodeName=deq2
    - SlurmctldHost=deq2
- Debugging: must `sudo` when checking i.e. `sudo journalctl -xeu slurmctld.service`
- Note: slurm prior to 20.11.7 or 20.02.7 are no longer available due to a security issue (Ubuntu dpkg is 19.x, has this been patched)
- install slurm with apt
-  This blog has some possibly good info for a standalone cluster on 20.04: 
  - https://blog.llandsmeer.com/tech/2020/03/02/slurm-single-instance.html
  - https://gist.github.com/ckandoth/2acef6310041244a690e4c08d2610423


#### deq2 (old)
```
ClusterName=vahydro
SlurmctldHost=deq2
MpiDefault=none
ProctrackType=proctrack/cgroup
ReturnToService=1
SlurmctldPidFile=/var/run/slurmctld.pid
SlurmctldPort=6817
SlurmdPidFile=/var/run/slurmd.pid
SlurmdPort=6818
SlurmdSpoolDir=/var/spool/slurmd
SlurmUser=slurm
StateSaveLocation=/var/spool/slurmctld
SwitchType=switch/none
TaskPlugin=task/affinity
InactiveLimit=0
KillWait=30
MinJobAge=300
SlurmctldTimeout=120
SlurmdTimeout=300
Waittime=0
SchedulerType=sched/backfill
SelectType=select/cons_tres
SelectTypeParameters=CR_Core
AccountingStorageType=accounting_storage/none
JobCompLoc=/opt/model/slurm/jobs.log
JobCompType=jobcomp/filetxt
JobAcctGatherFrequency=30
JobAcctGatherType=jobacct_gather/none
SlurmctldDebug=info
SlurmctldLogFile=/var/log/slurmctld.log
SlurmdDebug=info
SlurmdLogFile=/var/log/slurmd.log
NodeName=deq2 CPUs=1 CoresPerSocket=8 ThreadsPerCore=2 State=UNKNOWN
PartitionName=debug Nodes=ALL Default=YES MaxTime=INFINITE State=UP

```

**Comment by COBrogan** [comment]
Slurm Daemon donw -> check logs:
```
sudo systemctl restart slurmd
Job for slurmd.service failed because the control process exited with error code.
See "systemctl status slurmd.service" and "journalctl -xeu slurmd.service" for details.
nano /var/log/slurm/slurmdbd.log
```

Error in mySQL socket
```
[2026-04-22T06:25:40.290] error: mysql_real_connect failed: 2002 Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)
[2026-04-22T06:25:40.290] error: unable to re-connect to as_mysql database
```

Check my SQL config:
```
 sudo nano /etc/mysql/my.cnf

[client-server]
# Port or socket location where to connect
# port = 3306
socket = /run/mysqld/mysqld.sock
```

Try? `socket = /var/run/mysqld/mysqld.sock` -> No luck, reset the cnf file

**Comment by rburghol** [comment]
@COBrogan I restarted `mySQL` (mariadb), as what you discovered definitely pointed to that being an issue. It seemed to restart successfully however the `slurmd` service still failed, so we've got to keep digging.

**Comment by rburghol** [comment]
@COBrogan I think that I fixed this issue.  It appeared that the old `slurmd `process was simply hung, and thus, we could not restart it, and it was not responding to shutdown requests either.  Below is a transcript of how I got it to report a good status, and I also added this to the body of the issue above.  


- `systemctl status slurmd.service` showed slurmd: fatal: Unable to bind listen port (6818): Address already in use` (see **Table 1** for full output)
   - This is caused by a hung process, needed to terminate and restart
   - Find pid: `sudo ss -tulpn | grep :6818`
      - Returned: `tcp   LISTEN 1139   4096         0.0.0.0:6818      0.0.0.0:*    users:(("slurmstepd",pid=1402467,fd=5))`
   - Kill it: `sudo kill 1402467` (did not need to use `kill -9 ` option, but sometimes that is needed)
   - Restart: `sudo systemctl restart slurmd`
   - Check: `systemctl status slurmd.service` gave `Active: active (running) since Thu 2026-04-23 14:02:55 UTC; 6s ago`

**Table 1:**  Full output of `systemctl status slurmd.service` when old process is hung.
```
Apr 22 20:36:55 deq3 (slurmd)[2090632]: slurmd.service: Referenced but unset environment variable evaluates to an e>
Apr 22 20:36:55 deq3 slurmd[2090632]: slurmd: slurmd version 23.11.4 started
Apr 22 20:36:55 deq3 slurmd[2090632]: slurmd: error: Error binding slurm stream socket: Address already in use
Apr 22 20:36:55 deq3 slurmd[2090632]: slurmd: fatal: Unable to bind listen port (6818): Address already in use
Apr 22 20:36:55 deq3 systemd[1]: slurmd.service: Main process exited, code=exited, status=1/FAILURE
Apr 22 20:36:55 deq3 systemd[1]: slurmd.service: Failed with result 'exit-code'.
Apr 22 20:36:55 deq3 systemd[1]: Failed to start slurmd.service - Slurm node daemon.
```

**Comment by COBrogan** [comment]
As deq3 has been updated to DEQ1, I updated the slurm.conf file /etc/slurm/slurm.conf to replace all instances of deq3 with deq1. I confirmed no hardware changes via `slurmd -C`. After making the updates, I had to reconfigure slurm and restart the daemon on deq1:
```
sudo scontrol reconfigure
sudo systemctl restart slurmctld
sudo systemctl start slurmd
#Confirm no issues
show node=deq1
systemctl status slurmd
systemctl status slurmctld
```
